### ISSUE TITLE
External PRs cannot access secrets to run instrumentation tests.

### ISSUE THREAD

**Issue by JakeWharton** [android/android-ktx#141]

**Comment by JakeWharton** [comment]
@chrisbanes seems like you didn't solve this on Tivi either. Any ideas?

**Comment by chrisbanes** [comment]
There's a setting in the CircleCI project settings for this (Advanced Settings -> Pass secrets to builds from forked pull requests) but you can very easily leak your secrets. This is especially important here since we're using an Google billed Firebase account.

I think if we just make sure nothing is written to disk/log, we should be OK.

**Comment by oldergod** [comment]
> I think if we just make sure nothing is written to disk/log, we should be OK.

Isn't there the risk one rerun a build with SSH? All environment variables could be easily retrieved this way.

**Comment by chrisbanes** [comment]
@oldergod good point. More information: https://circleci.com/docs/1.0/fork-pr-builds/

**Comment by dovahkiin98** [comment]
How can we add PR then?
Should we wait until you find a solution?
Or is there a work around?

**Comment by JakeWharton** [comment]
AOSP is the target of contribution now.
