### ISSUE TITLE
Why sources are still in "java" folder?

### ISSUE THREAD

**Issue by Rokanank** [android/android-ktx#164]
It may be not so important, but why path to sources still contains **java**
android-ktx/src/main/java/androidx/

shouldn't it be kotlin?
android-ktx/src/main/kotlin/androidx/

**Comment by JakeWharton** [comment]
It doesn't really matter as the Kotlin plugin compiles from both by default. 'java' is chosen because AS recognizes it by default. We could configure the build such that it recognizes 'kotlin', but I'd rather minimize customizations we make instead.

If you want to see the 'kotlin' folder used, send an issue or PR to the Kotlin Gradle plugin to register the 'kotlin' folder as a source set with the 'android' plugin.

**Comment by joshfriend** [comment]
If you use the "Android" view in the Android Studio navigator panel, it shows "Java" as the folder name, even if you call it "kotlin" in your filesystem

![asdf](https://i.imgur.com/IrVQURN.png)
