### ISSUE TITLE
Why Not Something For Content Provider

### ISSUE THREAD

**Issue by m3sibti** [android/android-ktx#167]
Please Try To Solve The Headache Of content provider

**Comment by JakeWharton** [comment]
Unless you have a concrete proposal for something that could be added or a specific pain point that could be addressed I don't see much action to take here. There's little reason to use a content provider anyway unless you're providing a cross-app API. There are first-party and third-party solutions for persistence otherwise which do a much better job of abstracting the complexities.

**Comment by m3sibti** [comment]
Thanks for your help 😁
