### ISSUE TITLE
Mapping object and list of objects from Cursor

### ISSUE THREAD

**Issue by rakeeb11** [android/android-ktx#266]
Having a object mapper passed in as a lambda to Cursor might make the code more readable?

We'd have an API like so,
`val data = cursor.mapData { Data(cursor.getString("data")) }`

```
/**
 * Returns a mapped object of type [T]
 *
 * Used best in conjunction with [getData]
 * @param mapper Mapping logic for [T] with respect to the [Cursor]
 */
inline fun <T> Cursor.mapData(mapper: (Cursor) -> T): T? {
    var value: T? = null
    this.use {
        if (!moveToFirst()) return null
        if (!isAfterLast) {
            value = mapper(this)
            moveToNext()
        }
        return value
    }
}

/**
 * Returns a mapped [List] of type [T]
 *
 * Used best in conjunction with [getDataList]
 * @param mapper Mapping logic for [T] with respect to the [Cursor]
 */
inline fun <T> Cursor.mapDataList(mapper: (Cursor) -> T): List<T> {
    this.use {
        val list = arrayListOf<T>()
        if (!moveToFirst()) {
            return list
        }
        while (!isAfterLast) {
            list.add(mapper(this))
            moveToNext()
        }
        return list
    }
}
```

**Comment by JakeWharton** [comment]
Dupe of #201

**Comment by JakeWharton** [comment]
Why are you interacting with a cursor directly and not using a higher-level API like Room or SQL Brite/Delight?

**Comment by rakeeb11** [comment]
I actually love SQLDelight and Room! Just thought it would be more of a simple implementation without those libraries. Just like `getString()`, but I kinda see why you wouldn't want this to be there.

Does this also mean that it might not be a good idea for something like this too?

```
/**
 * Returns an object [T] from your database query [statement] and [selectionArgs]
 * along with the [mapper] for [T]
 */
inline fun <T> SQLiteDatabase.getData(
    statement: String,
    selectionArgs: Array<String>,
    mapper: Cursor.() -> T
): T? {
    return rawQuery(statement, selectionArgs).use { cursor ->
        cursor.mapData { mapper(cursor) }
    }
}

/**
 * Returns a [List] of [T] from your database query [statement] and [selectionArgs]
 * along with the [mapper] for [T]
 */
inline fun <T> SQLiteDatabase.getDataList(
    statement: String,
    selectionArgs: Array<String>,
    mapper: Cursor.() -> T
): List<T> {
    return rawQuery(statement, selectionArgs).use { cursor ->
        cursor.mapDataList { mapper(cursor) }
    }
}
```

**Comment by JakeWharton** [comment]
I think we're a bit hesitant to such things because while we want to add utilities that leverage the language like these, we also want to steer developers in the right direction. I wouldn't want to encourage using these _over_ something like SQL Brite/Delight or Room, and anyone interacting with Cursor has probably written these already in whatever language they're using. The line is very grey.

The existing extensions on Cursor were added because SQL Brite exposes a `Cursor -> T` type where they could be useful. I have no idea if Room ever exposes such things to you, but I doubt it. As we absorb SQL Brite's functionality into SQL Delight the need for these will go down, so maybe I shouldn't have added them. I suppose it was a bit of an abuse of my power as contributor to both, but why did I join Google if not to occasionally do this.

**Comment by rakeeb11** [comment]
Yes! makes a lot of sense regarding the influence that the library will have over developers. Will close the issue now 👍
