### ISSUE TITLE
View onClick proposal

### ISSUE THREAD

**Issue by andrey-shikhov** [android/android-ktx#288]
Suggestion:
I View, which was clicked, is not required to handle the event

    var View.onClick: (() -> Unit)
            get() = throw UnsupportedOperationException()
            set(value) = this.setOnClickListener { value() }

Result: ```button.onClick = ::onSomeActionClick```

II View, which was clicked, is not required to handle the event and action is too simple to make separated method handler

    fun View.onClick(onClick: () -> Unit) {
        this.onClick = onClick
    }

Result: ```button.onClick { Toast.makeText(context, "hello!", Toast.LENGTH_SHORT).show() }```

III View, which was clicked, is required to handle action

    var View.onViewClick: ((view: View) -> Unit)
        get() = throw UnsupportedOperationException()
        set(value) = this.setOnClickListener(value)

Result: 

     button.onViewClick {
         it.isVisible = false
     }

**Comment by rongi** [comment]
Why do we need this? Because it's shorter, less noise. Our developers love it.

view.onClick {
    // do magic!
}

**Comment by JakeWharton** [comment]
Are we going to do this for every listener in the entire platform then? Is
that really of value?

**Comment by rongi** [comment]
Is `onClick() { }` preferred over `setOnClickListener()  { }`? I would say it's preferred: it's shorter, it has simpler meaning because it mentions one less semantic entity (listener), it's in more functional style. Maybe it's worth to promote this way of doing things by making one of the most used functions in Android follow this convention?

**Comment by JakeWharton** [comment]
I'm not denying that it's preferred. I'm asking if it's of value. Its only benefit is fewer characters to read. It's not fewer to type since both are easily auto-completable with 3 or 4 chars. If we were to do this we would have to do it for the hundreds of other SAM listeners. That seems like a waste of our time and a pain to maintain.

**Comment by rongi** [comment]
It doesn't make sense to support hundreds of listeners for sure. Why implementing it just for a handful of listeners isn't an option? Is it because of some policy in Google? Or because it's just a proper way to do the job?

**Comment by JakeWharton** [comment]
That handful of listeners is different for every person. We'll be endlessly
fielding requests for new short listener aliases and having to make
decisions about which are worthwhile or not based on arbitrary criteria.
It's asymptotic for sure, but there's no easy way to say no at a certain
point. It also means we have to track listeners in new versions of Android
and pre-determine whether or not we think they'll be popular enough.
