### ISSUE TITLE
how to choose inline or outline for ext fun

### ISSUE THREAD

**Issue by yizeliang** [android/android-ktx#322]

**Comment by romainguy** [comment]
Could you describe in more detail what you are proposing please? Thanks!

**Comment by yizeliang** [comment]
@romainguy I want to know what the principles of using inline functions and using ordinary functions are. How do you choose

```kotlin

inline fun inF(){}

fun F(){}

```
How to use inline properly,Thanks.

**Comment by JakeWharton** [comment]
This is a general question not specific to this library so I would recommend seeking guidance in a more general forum. For this library, most things are inline as they're aliases to existing public APIs you could otherwise call directly. Anything non-inline is likely due to the desire to not bloat the code when the implementation is sufficiently complex.

**Comment by yizeliang** [comment]
Thanks,I probably know how to deal with it
