### ISSUE TITLE
Use ContextCompat.getSystemService in Context.kt

### ISSUE THREAD

**Issue by JakeWharton** [android/android-ktx#450]
To remove `@RequiresApi(23)` from reified `systemService` helper once we can depend on the 28 support library.

**Comment by JakeWharton** [comment]
This happened. Hasn't be synchronized out yet though.

**Comment by Thomas-Vos** [comment]
@JakeWharton Thanks for system service extension. However, because of a bug I can't use it. ContextCompat has a bug for the system services on older API levels.

For example: `NSD_SERVICE` was added in API 16. This is the source code of ContextCompat:

```
if (Build.VERSION.SDK_INT > 16) {
    ...
    SERVICES.put(NsdManager.class, NSD_SERVICE);
}
```
This is not correct, the if checks should be `>=`. All of the API level checks in that method are incorrect. Has this been fixed already in a newer version which isn't released yet?

EDIT: See issue: https://issuetracker.google.com/issues/116074337
