### ISSUE TITLE
The README examples don't say why it is better

### ISSUE THREAD

**Issue by salamanders** [android/android-ktx#462]
Everything before the `doOnPreDraw` example was roughly the same number of lines and left me not quite getting why this way was better.

Either: 

1. More explicit "why this change is a good change" comments if the number of lines or characters are about the same.
2. Start with more examples that reduce the amount of code.

**Comment by JakeWharton** [comment]
That specific example enables the use of a lambda and removes the ceremony of adding/removing the listener instance.

**Comment by JakeWharton** [comment]
Sent a PR to clarify this in the opening quip

**Comment by salamanders** [comment]
My counting fingers are often wrong, that is why I like computers.  

Agreed: doOnPreDraw removes lots of boilerplate!  It was the others that had an unclear value prop.

1. `Uri.parse(myUriString)` vs `myUriString.toUri()` - why is extending the string better?  Less imports?  Always available?
2. `sharedPreferences.edit { putBoolean("key", value) }` - does this allow multiple changes?  Are lambdas in general better?  More kotlin-ish?  Removing the "apply()" is worth it?

But my real question was a high-level:

> The goal of Android KTX is to make Android development with Kotlin more concise, pleasant, and idiomatic by leveraging the features of the language such as extension functions/properties, lambdas, named parameters, and parameter defaults. 

Great!  But... if Kotlin is a first-class language for Android, why is this the job of a library, as opposed to all of those goals being core-AOSP goals?  Or is this library the official layer on top of Android that makes Kotlin Android Dev as friendly as Kotlin allows?

**Comment by JakeWharton** [comment]
1. Discoverability as the IDE auto-completes this for you whereas you have to know the first function exists and on which type.

    It also changes the order of components to allow chaining in a way that it's still readable. Which is easier to comprehend:

    ```java
    Records.list(Dns.resolve(Uri.parse(host)))
    ```
    ```kotlin
    host.toUri().resolveDns().listRecords()
    ```

    The latter provides easy comprehension of the subject when reading from left-to-right, as we do, whereas the former requires building up a stack of operations from left-to-right where the subject changes from right-to-left.

 2. Yes it allows multiple changes. The documentation details this. Removing the apply is worth it because you have to remember to call it whereas here you don't? You'll never forget to apply a preference edit, show a toast, mark a DB transaction sucessful, etc. by removing the ceremony of API interaction and encapsulating behind language constructs like higher-order functions.

    We could do this in Java, sure, but it's required tooling to backport lambdas to work on API levels prior to 24 and it also incurs a cost in dex size and heap size as a class is generated and must be instantiated. Kotlin requires neither of these things so the abstraction which simplifies the API becomes zero-cost.

The Android framework will be written in Java for the foreseeable future for various technical reasons. We would lose a great deal of the appeal of Kotlin if Android was to do something as naive as bundling the Kotlin stdlib and exposing it. There are efforts underway to remove the need for a large majority of the explicit declarations of this library, but they will take far longer than we're comfortable doing nothing which is why this library exists.
