### ISSUE TITLE
SpannableStringBuilder.kt | index customization

### ISSUE THREAD

**Issue by uburoiubu** [android/android-ktx#478]
Why it does not allow to customize start and end indexes (when, for instance, you don't need to append anything, but to span already appended text)?

**Comment by JakeWharton** [comment]
If you don't need to build a string but just want to apply spans to one you can call toSpannable() on the string and then use the functions on Spannable or the extensions we provide on Spannable to add spans.

**Comment by JakeWharton** [comment]
Precisely! Does that meet your needs?

**Comment by uburoiubu** [comment]
@JakeWharton, yes, but I'd prefer it in a builder way, like you're doing here:

`val builder = SpannableStringBuilder(urlString)       
   .bold { italic { underline { append("hi there") } } } `

Something like that:

`"Hello, World".toSpannable().bold(0, 5)`

**Comment by JakeWharton** [comment]
The builder is modeled as a DSL because it need to capture the starting and ending index before you call `append` with text. A nice property of this is that custom spans and the built-in helper have the same calling convention:
```kotlin
val string = buildSpannedString {
  inSpan(CustomSpan()) {
    append("hi")
  }
  bold {
    append("bye")
  }
}
```

But when you have a raw `Spannable`, you're only ever dealing with indices. If we provide a helper such as one you are providing, when you mix it with custom spans you get two different calling conventions even when invoking from a builder:
```kotlin
val string = "hibye".toSpannable()
    .apply { set(0, 2, CustomSpan()) }
    .bold(2, 5)
```
Now we could correct this by adding a builder-like method for custom spans:
```kotlin
val string = "hibye".toSpannable()
    .span(0, 2, CustomSpan())
    .bold()
```
but then we still have the ability to manipulate spans on a `Spannable` this way:
```kotlin
val string = "hibye".toSpannable()
string[0:2] = StyleSpan(BOLD)
string[2:5] = CustomSpan()
```
I'll also note that there's a shorthand form of specifying a span on the entire `Spannable`:
```kotlin
val string = "hibye".toSpannable()
string += CustomSpan()
```

I don't like the idea of having two ways to accomplish the same task so I don't want to add a second means of doing this without either covering use cases that are currently impossible (which doesn't seem the case) or removing the current API (provided this technique covers all use cases of it).

**Comment by uburoiubu** [comment]
Makes sense to me. Thanks
