### ISSUE TITLE
Extension functions should be used only when they relate closely to the classes they are extending

### ISSUE THREAD

**Issue by RaisedByTheInternet** [android/android-ktx#488]
For example, I'm not convinced that it makes sense for [String.parseAsHtml](https://github.com/android/android-ktx/blob/562cc5ac2489678a3ad65f708fc509bf6b47b646/src/main/java/androidx/core/text/Html.kt#L39) to be an extension of String, because this function is not closely related to basic idea of a String.

The following code surprises me:

    "".parseAsHtml()
    // the type of the above expression is android.text.Spanned

The following, on the other hand, doesn't seem as weird:

    parseAsHtml("")
    // the type of the above expression is android.text.Spanned

**Comment by dimsuz** [comment]
I had the same itch when I saw an addition of `Context.toast()` to the extension list. Toast is not something I perceive as a functionality of `Context`. Though I admit that sometimes this line between usefulness and relatedness is very thin, so I'm not sure I would argue in whichever direction in both these cases.

**Comment by knordbo** [comment]
I have similar concern which extensions such as `String.toUri()`. I'm not sure if it scales if each kotlin library adds library specific extensions to Java Platform APIs. It would work fine if the library was modular enough to be consumed as `<library>-ext`  and `<library>-jre-ext` so that those extensions are optional, but this added complexity/confusion on the consumer of the library might not be worth it. If so it's probably safer to not add such extensions. 

Totally fan of all the Android specific extensions on the other hand 👍

**Comment by gc2964** [comment]
-

**Comment by JakeWharton** [comment]
I think you'd have a better argument if `Html` was a type that you were forced to configure and which was then required for conversion. Then it would be an instance function on `Html` rather than a static and we wouldn't be having this conversation at all!

That being said, I think the extension would also have a better argument for staying how it is if `Html` was the representation type that was returned rather than `Spannable` because then it would be a conversion function that could be named with parity of all the others (`toHtml`).

I don't feel too strongly either way, but it's easy to argue for it being an extension which is why I went with it:

 1. It operates on a single type, `String`. The Kotlin language conventions [strongly recommend][1] the use of an extension in this case.
 2. Discoverability of the functionality is greatly increased in the IDE by virtue of it being available to auto-complete on the receiver type rather than requiring prior knowledge of the functions existence to use it via the original function or as a top-level function.
 3. Behavior configuration is achieved through optional arguments for which we can supply reasonable defaults. This enables the use of a language features (default arguments and named parameters) whereas using the backing function directly would not.
 4. It's fundamentally a two-way conversion process. The only thing that makes it different than the normal ones is that there is no dedicated type. This is why the regular naming convention isn't used.

@dimsuz I _really_ don't like the `Toast` ones and will likely be advocating for their removal in the 1.0 API stabilization hunger games. It received a high number of requests (despite that fact that you really should never use toasts). If you have an issue with a specific API, file a dedicated issue about it so the discussion can be localized in one place.

@knordbo That extension is Android specific as `Uri` is an Android type. If you have an issue with a specific API, file a dedicated issue about it so the discussion can be localized in one place.

 [1]: https://kotlinlang.org/docs/reference/coding-conventions.html#using-extension-functions

**Comment by JakeWharton** [comment]
All of these extensions have gone through our API council. You might have noticed some changes in alpha03 or beta01 which brought the deprecation and now removal of a bunch of existing ones and some changes to others. For better or worse, this is what the Kotlin language has chosen as its primary means of exposing added functionality to other types.

Also, `toast` is gone. I even switched sides and argued on its behalf in the API council meeting to make sure its removal was justified.
