### ISSUE TITLE
Why made every method inline?

### ISSUE THREAD

**Issue by tysheng** [android/android-ktx#492]
Seems some of them don't need inline, is there something tricky?

**Comment by JakeWharton** [comment]
All the extensions are aliases to public APIs that you otherwise would be using. There's no need to introduce a static method trampoline that the code has to jump through. They're small so it doesn't contribute to code bloat. Additionally it lets us break binary compatibility without actually breaking binary compatibility as no one's code actually contains a binary reference to our signatures.
