### ISSUE TITLE
sparseArrayOf(), sparseBooleanArrayOf(), etc.

### ISSUE THREAD

**Issue by abyrnes** [android/android-ktx#521]
Add functions similar to those found in `kotlin.collections` to create a `SparseArray`, `SparseBooleanArray`, etc.

```kotlin
sparseArrayOf(1 to "one", 2 to "two")

sparseIntArrayOf(1 to 2, 2 to 3)
```

**Comment by JakeWharton** [comment]
The reason these weren't included is because these collections exist to eliminate boxing. By creating a factory like this you force boxing when the primitive is put into a `kotlin.Pair` and then unboxing when they're transferred to the collection.

In a world where we wanted to combat boxing (and didn't care about the allocation of the pairs or vararg array as we don't with the others) we could ideally overload `to` with primitive specializations, but because the built-in one is in a default package it will always be preferred.

Are you creating these instances and then never mutating them? Or are you just seeding instances which are then mutated over time?

**Comment by abyrnes** [comment]
I can't imagine a good use case for creating the instances and never mutating them. As for seeding, I can imagine a case where the seeded values can be overridden in a meaningful way.

Ktx already provides the index operator for these collections which is more efficient and achieves the same thing but is less idiomatic.

The was merely a suggestion to make the initialization syntax similar to what kotlin provides for maps in its standard library, especially since `SparseArray` is often marketed as "a replacement for HashMap with integer keys with a performance gain". But the cost does seem a bit high for very little gain.

**Comment by JakeWharton** [comment]
I'm going to close this for now based on the limited support and limitations around allocation/boxing.
