### ISSUE TITLE
Can't use getString(String) : String

### ISSUE THREAD

**Issue by alfianyusufabdullah** [android/android-ktx#591]
Hi

I'm trying use ext from `Cursor` like this

`val _id = cursor.getString("_id")`

but getting error like this

> using 'getString(String) : String' is an error, Use an abstraction like room or look up

how to handle it ?

**Comment by JakeWharton** [comment]
These extensions are being removed. They remain in the code for binary compatibility but will be removed for 1.0 stable. The error message tells you to use a library like SQL Delight or Room, or to prefer doing the column name to index mapping once and caching it rather than something like this extension which has do to that lookup (and its multiple JNI calls) each time.

**Comment by PaulWoitaschek** [comment]
Hm I don't like this change. I use this a lot in room migrations.
